services:
  app:
    image: library-platform-image
    container_name: library-platform-backend-app
    ports:
      - '5000:5000'
    extra_hosts:
      # Otherwise backend will see only docker host not main host,
      # so we need to refer to main machine through veth/bridge in this way.
      # Done by hard way!
      - 'host.docker.internal:host-gateway'
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
