name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # image names
  BACKEND_IMAGE_NAME: ${{ github.repository_owner }}/devopslab5-backend
  DATABASE_IMAGE_NAME: ${{ github.repository_owner }}/devopslab5-database

jobs:
  # check (work for PR and Push)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend (check only)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build DB (check only)
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # push images (only for Push, ingore PR)
  push-to-registry:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # backend
      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          provenance: false

      # database
      - name: Extract metadata for DB
        id: meta-db
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: ${{ steps.meta-db.outputs.tags }}
          labels: ${{ steps.meta-db.outputs.labels }}
          provenance: false

  # deploy to DEV (only by Push to Dev)
  deploy-dev:
    needs: push-to-registry
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_DEV_HOST }}
          username: ${{ secrets.SERVER_DEV_USER }}
          key: ${{ secrets.SERVER_DEV_SSH_KEY }}
          script: |
            cd /srv/libproj/
            mkdir -p monitoring
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.yml -o docker-compose.yml
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/monitoring/prometheus.yml -o monitoring/prometheus.yml
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/monitoring/promtail.yml -o monitoring/promtail.yml
            docker compose pull
            docker compose --env-file environment.cfg up -d --remove-orphans

  # deploy to Main (only by Push to Main)
  deploy-main:
    needs: push-to-registry
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Main server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_MAIN_HOST }}
          username: ${{ secrets.SERVER_MAIN_USER }}
          key: ${{ secrets.SERVER_MAIN_SSH_KEY }}
          script: |
            cd /srv/libproj/
            mkdir -p monitoring
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.yml -o docker-compose.yml
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/monitoring/prometheus.yml -o monitoring/prometheus.yml
            curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/monitoring/promtail.yml -o monitoring/promtail.yml
            docker compose pull
            docker compose --env-file environment.cfg up -d --remove-orphans
